// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlwbcjhkejfsnvolsufj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sd2JjamhrZWpmc252b2xzdWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2OTkwOTYsImV4cCI6MjA1NzI3NTA5Nn0.Xoer1BlXwkp7RPm4cxfFFRkwWfU7IZkY-8Vp0BSjv6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);