// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmpfbxpgumazvxwbqliv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcGZieHBndW1henZ4d2JxbGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzQ3MzYsImV4cCI6MjA1ODUxMDczNn0.rAQuisto0nZiLMXwU1Vi8dX9wippQ7eAsjSZHQ3Rdws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);